#!/usr/bin/env bash
# Creates the hermetic DSH_HOME and the `scrum` profile inside this repository.
# Idempotent: reruns refresh the symlinks.
#
# Usage:  bash scripts/setup-profile.sh
# Then:   bash scripts/serve.sh   (boots the web GUI with the scrum profile)

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOME_DIR="$REPO/.dsh-home"
PROFILE="$HOME_DIR/profiles/scrum"

mkdir -p "$PROFILE/node_modules/@scrum-harness"

cat > "$PROFILE/package.json" <<'JSON'
{
  "name": "dsh-profile-scrum",
  "private": true,
  "dependencies": {
    "@scrum-harness/bundle": "file:../../../packages/bundle-scrum"
  },
  "dsh": {
    "profile": {
      "bundles": [
        "@deepseek-ai/dsh-base",
        "@deepseek-ai/dsh-web-app",
        "@scrum-harness/bundle"
      ]
    }
  }
}
JSON

# User patch layer of the scrum profile: share the REAL harness home's
# settings and credential documents (both plugins take a configurable path and
# hot-reload), so the Anthropic sign-in, API keys and default model made on
# the normal harness work here too. Sessions/storages stay in .dsh-home.
REAL_DSH_HOME="${REAL_DSH_HOME:-$HOME/.dsh}"
cat > "$PROFILE/cordis.patch.yml" <<PATCH
# Generated by scripts/setup-profile.sh — rerun it to refresh.
# Shares the real harness home's settings and credentials with this profile.
- id: settings
  config:
    path: $REAL_DSH_HOME/settings.yaml
- id: credentials
  config:
    path: $REAL_DSH_HOME/.credentials.yaml
PATCH

for pkg in bundle-scrum scrum-domain scrum-probe tool-scrum command-scrum scrum-api ui-scrum; do
  case "$pkg" in
    bundle-scrum) name="bundle" ;;
    scrum-domain) name="domain" ;;
    scrum-probe) name="probe" ;;
    ui-scrum) name="ui" ;;
    *) name="$pkg" ;;
  esac
  if [ -d "$REPO/packages/$pkg" ]; then
    ln -sfn "$REPO/packages/$pkg" "$PROFILE/node_modules/@scrum-harness/$name"
  fi
done

echo "Profile ready: $PROFILE"
echo "Boot with: bash scripts/serve.sh"
